Travis CI: Reverted to using `language: haskell`
https://github.com/travis-ci/travis-ci/issues/4393 seems to be solved
Removed the trick to seperate caches.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,15 +1,15 @@
 sudo: false
 
-language: c
+language: haskell
+
+ghc:
+  - 7.10
+  - 7.8
+  - 7.6
 
 addons:
   apt:
-    sources:
-      - hvr-ghc
     packages:
-      - ghc-7.6.3
-      - ghc-7.8.4
-      - ghc-7.10.2
       - cabal-install-1.20
       - cabal-install-1.22
       # test dependencies
@@ -17,24 +17,25 @@ addons:
       - cppcheck
       - hscolour
 
+env:
+  - TESTS="test_c"
+
 matrix:
   include:
-    - env: CABALVER="1.20" GHCVER="7.6.3" TESTS="test_c"
-      # separate caches for different compiler versions
-      # until https://github.com/travis-ci/travis-ci/issues/4393 is resolved
-      compiler: ": #GHC 7.6.3"
+    - env: CABALVER="1.20" TESTS="test_c"
+      ghc: 7.6
     # - env: CABALVER="1.20" GHCVER="7.8.4" TESTS="lib_doc doc"
     #   compiler: ": #GHC 7.8.4"
     # - env: CABALVER="1.20" GHCVER="7.8.4" TESTS="test_js"
     #   compiler: ": #GHC 7.8.4"
-    - env: CABALVER="1.20" GHCVER="7.8.4" TESTS="test_c"
-      compiler: ": #GHC 7.8.4"
+    - env: CABALVER="1.20" TESTS="test_c"
+      ghc: 7.8
     # - env: CABALVER="1.22" GHCVER="7.10.2" TESTS="lib_doc doc"
     #   compiler: ": #GHC 7.10.2"
     # - env: CABALVER="1.22" GHCVER="7.10.2" TESTS="test_js"
     #   compiler: ": #GHC 7.10.2"
-    - env: CABALVER="1.22" GHCVER="7.10.2" TESTS="test_c"
-      compiler: ": #GHC 7.10.2"
+    - env: CABALVER="1.22" TESTS="test_c"
+      ghc: 7.10
 
 cache:
   directories:
@@ -46,49 +47,52 @@ before_cache:
   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
 
 before_install:
+  # What is this for?
   - unset CC
-  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
+  # I highly doubt this is useful (at least the GHC bit)
+  - export PATH=/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
   - env
 
 install:
-  - cabal --version
-  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-  - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
-    then
-      zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
-          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-    fi
-  - travis_retry cabal update -v
-  # Run build with 2 parallel jobs
-  # The container environment reports 16 cores,
-  # causing cabal's default configuration (jobs: $ncpus)
-  # to run into the GHC #9221 bug which can result in longer build-times.
-  - sed -i -r 's/(^jobs:).*/\1 2/' $HOME/.cabal/config
-  - cabal install -f FFI --only-dependencies --enable-tests --dry -v > installplan.txt
-  - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
+  - cabal install --only-dependencies --enable-tests -f FFI
+  # Same thing
+  # - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  # - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+  #   then
+  #     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+  #         $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+  #   fi
+  # - travis_retry cabal update -v
+  # # Run build with 2 parallel jobs
+  # # The container environment reports 16 cores,
+  # # causing cabal's default configuration (jobs: $ncpus)
+  # # to run into the GHC #9221 bug which can result in longer build-times.
+  # - sed -i -r 's/(^jobs:).*/\1 2/' $HOME/.cabal/config
+  # - cabal install -f FFI --only-dependencies --enable-tests --dry -v > installplan.txt
+  # - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
 
-  # check whether current requested install-plan matches cached package-db snapshot
-  - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
-    then
-      echo "cabal build-cache HIT";
-      rm -rfv .ghc;
-      cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
-      cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
-    else
-      echo "cabal build-cache MISS";
-      rm -rf $HOME/.cabsnap;
-      mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
-      cabal install -f FFI --only-dependencies --enable-tests;
-    fi
+  # # check whether current requested install-plan matches cached package-db snapshot
+  # - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
+  #   then
+  #     echo "cabal build-cache HIT";
+  #     rm -rfv .ghc;
+  #     cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
+  #     cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
+  #   else
+  #     echo "cabal build-cache MISS";
+  #     rm -rf $HOME/.cabsnap;
+  #     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+  #     cabal install -f FFI --only-dependencies --enable-tests;
+  #   fi
 
-  # snapshot package-db on cache miss
-  - if [ ! -d $HOME/.cabsnap ];
-    then
-      echo "snapshotting package-db to build-cache";
-      mkdir $HOME/.cabsnap;
-      cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
-      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
-    fi
+  # # snapshot package-db on cache miss
+  # - if [ ! -d $HOME/.cabsnap ];
+  #   then
+  #     echo "snapshotting package-db to build-cache";
+  #     mkdir $HOME/.cabsnap;
+  #     cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
+  #     cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
+  #   fi
 
 before_script:
   - cabal sdist
